export const CNAB_SCHEMA_SEGMENTO_P = {
  segmento_p: {
    id: "segmento_p",
    label: "Segmento P - Título",
    segmento_id: "P",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco", ruleId: "G001" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote", ruleId: "G002" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3", ruleId: "G003" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Sequencial", ruleId: "G038" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "P", ruleId: "G039" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 15, type: "A", label: "Reservado", ruleId: "G004" },
      { name: "codigo_movimento", start: 16, end: 17, type: "N", label: "Movimento", ruleId: "C004" },
      { name: "agencia_mantenedora", start: 18, end: 22, type: "N", label: "Agência", ruleId: "G008" },
      { name: "agencia_dv", start: 23, end: 23, type: "A", label: "DV Agência", ruleId: "G009" },
      { name: "numero_conta", start: 24, end: 35, type: "N", label: "Conta", ruleId: "G010" },
      { name: "conta_dv", start: 36, end: 36, type: "A", label: "DV Conta", ruleId: "G011" },
      { name: "agencia_conta_dv", start: 37, end: 37, type: "A", label: "DV Ag/Conta", ruleId: "G012" },
      { name: "nosso_numero", start: 38, end: 57, type: "A", label: "Nosso Número", ruleId: "G043" },
      { name: "codigo_carteira", start: 58, end: 58, type: "N", label: "Carteira", ruleId: "C006" },
      { name: "forma_cadastramento", start: 59, end: 59, type: "N", label: "Cadastramento" },
      { name: "tipo_documento", start: 60, end: 60, type: "A", label: "Tipo Documento", ruleId: "C008" },
      { name: "identificacao_emissao", start: 61, end: 61, type: "N", label: "Emissão" },
      { name: "identificacao_entrega", start: 62, end: 62, type: "N", label: "Entrega" },
      { name: "numero_documento", start: 63, end: 77, type: "A", label: "Nº Documento", ruleId: "C011" },
      { name: "data_vencimento", start: 78, end: 85, type: "N", label: "Vencimento", ruleId: "C012" },
      { name: "valor_titulo", start: 86, end: 100, type: "N", label: "Valor Nominal", ruleId: "P010" },
      { name: "agencia_cobradora", start: 101, end: 105, type: "N", label: "Ag. Cobradora" },
      { name: "agencia_cobradora_dv", start: 106, end: 106, type: "A", label: "DV Ag. Cobr." },
      { name: "especie_titulo", start: 107, end: 108, type: "N", label: "Espécie", ruleId: "C015" },
      { name: "aceite", start: 109, end: 109, type: "A", label: "Aceite" },
      { name: "data_emissao", start: 110, end: 117, type: "N", label: "Emissão", ruleId: "G016" },
      { name: "juros_mora_codigo", start: 118, end: 118, type: "N", label: "Cód. Juros", ruleId: "C018" },
      { name: "juros_mora_data", start: 119, end: 126, type: "N", label: "Data Juros" },
      { name: "juros_mora_taxa", start: 127, end: 141, type: "N", label: "Taxa Juros" },
      { name: "desconto1_codigo", start: 142, end: 142, type: "N", label: "Cód. Desc.", ruleId: "C021" },
      { name: "desconto1_data", start: 143, end: 150, type: "N", label: "Data Desc." },
      { name: "desconto1_taxa", start: 151, end: 165, type: "N", label: "Taxa Desc." },
      { name: "valor_iof", start: 166, end: 180, type: "N", label: "IOF" },
      { name: "valor_abatimento", start: 181, end: 195, type: "N", label: "Abatimento" },
      { name: "identificacao_titulo_empresa", start: 196, end: 220, type: "A", label: "ID Empresa" },
      { name: "codigo_protesto", start: 221, end: 221, type: "N", label: "Cód. Protesto", ruleId: "C026" },
      { name: "prazo_protesto", start: 222, end: 223, type: "N", label: "Prazo Protesto" },
      { name: "codigo_baixa", start: 224, end: 224, type: "N", label: "Cód. Baixa", ruleId: "C028" },
      { name: "prazo_baixa", start: 225, end: 227, type: "N", label: "Prazo Baixa" },
      { name: "codigo_moeda", start: 228, end: 229, type: "N", label: "Moeda", ruleId: "G065" },
      { name: "numero_contrato", start: 230, end: 239, type: "N", label: "Contrato", ruleId: "C030" },
      { name: "uso_exclusivo_febraban_2", start: 240, end: 240, type: "A", label: "Reservado", ruleId: "G004" }
    ]
  }
};
