export const CNAB_SCHEMAS = {
  header_arquivo: {
    label: "Header de Arquivo",
    fields: [
      { name: "banco", start: 1, end: 3, type: "N", label: "Código do Banco", pad: "0", rule: "isNumeric" },
      { name: "lote", start: 4, end: 7, type: "N", label: "Lote de Serviço", default: "0000", pad: "0" },
      { name: "registro", start: 8, end: 8, type: "N", label: "Tipo de Registro", default: "0" },
      { name: "uso_exclusivo_febraban_1", start: 9, end: 17, type: "A", label: "Uso Exclusivo FEBRABAN", pad: " " },
      { name: "empresa_inscricao_tipo", start: 18, end: 18, type: "N", label: "Tipo de Inscrição da Empresa", rule: "validateInscricaoTipo" },
      { name: "empresa_inscricao_numero", start: 19, end: 32, type: "N", label: "Número de Inscrição da Empresa", pad: "0", rule: "validateCNPJ_CPF" },
      { name: "convenio", start: 33, end: 52, type: "A", label: "Código do Convênio no Banco", pad: " " },
      { name: "agencia", start: 53, end: 57, type: "N", label: "Agência Mantenedora", pad: "0" },
      { name: "agencia_dv", start: 58, end: 58, type: "A", label: "Dígito Verificador da Agência" },
      { name: "conta", start: 59, end: 70, type: "N", label: "Número da Conta Corrente", pad: "0" },
      { name: "conta_dv", start: 71, end: 71, type: "A", label: "Dígito Verificador da Conta" },
      { name: "agencia_conta_dv", start: 72, end: 72, type: "A", label: "Dígito Verificador da Ag/Conta" },
      { name: "empresa_nome", start: 73, end: 102, type: "A", label: "Nome da Empresa", pad: " " },
      { name: "banco_nome", start: 103, end: 132, type: "A", label: "Nome do Banco", pad: " " },
      { name: "uso_exclusivo_febraban_2", start: 133, end: 142, type: "A", label: "Uso Exclusivo FEBRABAN", pad: " " },
      { name: "arquivo_codigo", start: 143, end: 143, type: "N", label: "Código Remessa/Retorno", default: "1" },
      { name: "arquivo_data", start: 144, end: 151, type: "N", label: "Data de Geração", rule: "validateDate" },
      { name: "arquivo_hora", start: 152, end: 157, type: "N", label: "Hora de Geração", rule: "validateTime" },
      { name: "arquivo_sequencial", start: 158, end: 163, type: "N", label: "Nº Sequencial do Arquivo" },
      { name: "layout_arquivo", start: 164, end: 166, type: "N", label: "Nº da Versão do Layout", default: "103" },
      { name: "densidade_arquivo", start: 167, end: 171, type: "N", label: "Densidade de Gravação" },
      { name: "reservado_banco", start: 172, end: 191, type: "A", label: "Para Uso Reservado do Banco" },
      { name: "reservado_empresa", start: 192, end: 211, type: "A", label: "Para Uso Reservado da Empresa" },
      { name: "uso_exclusivo_febraban_3", start: 212, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", pad: " " },
    ]
  },
  segmento_p: {
    label: "Segmento P - Dados do Título",
    segmento_id: "P",
    fields: [
      { name: "banco", start: 1, end: 3, type: "N", label: "Código do Banco" },
      { name: "lote", start: 4, end: 7, type: "N", label: "Lote de Serviço" },
      { name: "registro", start: 8, end: 8, type: "N", label: "Tipo de Registro", default: "3" },
      { name: "numero_registro", start: 9, end: 13, type: "N", label: "Nº Sequencial do Registro" },
      { name: "segmento", start: 14, end: 14, type: "A", label: "Código Segmento", default: "P" },
      { name: "filler", start: 15, end: 15, type: "A", label: "Uso Exclusivo FEBRABAN" },
      { name: "movimento_codigo", start: 16, end: 17, type: "N", label: "Código Instrução Movimento" },
      { name: "agencia", start: 18, end: 22, type: "N", label: "Agência Mantenedora" },
      { name: "agencia_dv", start: 23, end: 23, type: "A", label: "Dígito Verificador da Agência" },
      { name: "conta", start: 24, end: 35, type: "N", label: "Número da Conta" },
      { name: "conta_dv", start: 36, end: 36, type: "A", label: "Dígito Verificador da Conta" },
      { name: "agencia_conta_dv", start: 37, end: 37, type: "A", label: "Dígito Verificador da Ag/Conta" },
      { name: "nosso_numero", start: 38, end: 57, type: "A", label: "Nosso Número" },
      { name: "carteira", start: 58, end: 58, type: "N", label: "Código da Carteira" },
      { name: "cadastramento", start: 59, end: 59, type: "N", label: "Forma de Cadastramento" },
      { name: "documento_tipo", start: 60, end: 60, type: "A", label: "Tipo de Documento" },
      { name: "emissao_bloqueto", start: 61, end: 61, type: "N", label: "Identificação da Emissão do Bloqueto" },
      { name: "distribuicao_bloqueto", start: 62, end: 62, type: "A", label: "Identificação da Distribuição" },
      { name: "numero_documento", start: 63, end: 77, type: "A", label: "Número do Documento de Cobrança" },
      { name: "vencimento", start: 78, end: 85, type: "N", label: "Data de Vencimento", rule: "validateDate" },
      { name: "valor_titulo", start: 86, end: 100, type: "N", label: "Valor Nominal do Título", rule: "validateCurrency" },
      { name: "agencia_cobradora", start: 101, end: 105, type: "N", label: "Agência Encarregada da Cobrança" },
      { name: "agencia_cobradora_dv", start: 106, end: 106, type: "A", label: "Dígito Verificador da Agência" },
      { name: "especie_titulo", start: 107, end: 108, type: "N", label: "Espécie do Título" },
      { name: "aceite", start: 109, end: 109, type: "A", label: "Identificação de Aceite" },
      { name: "data_emissao", start: 110, end: 117, type: "N", label: "Data da Emissão do Título", rule: "validateDate" },
      { name: "juros_codigo", start: 118, end: 118, type: "N", label: "Código do Juros de Mora" },
      { name: "juros_data", start: 119, end: 126, type: "N", label: "Data do Juros de Mora" },
      { name: "juros_valor", start: 127, end: 141, type: "N", label: "Juros de Mora por Dia/Taxa" },
      { name: "desconto1_codigo", start: 142, end: 142, type: "N", label: "Código do Desconto 1" },
      { name: "desconto1_data", start: 143, end: 150, type: "N", label: "Data do Desconto 1" },
      { name: "desconto1_valor", start: 151, end: 165, type: "N", label: "Valor/Percentual a ser Concedido" },
      { name: "valor_iof", start: 166, end: 180, type: "N", label: "Valor do IOF a ser Recolhido" },
      { name: "valor_abatimento", start: 181, end: 195, type: "N", label: "Valor do Abatimento" },
      { name: "identificacao_titulo_empresa", start: 196, end: 220, type: "A", label: "Identificação do Título na Empresa" },
      { name: "codigo_protesto", start: 221, end: 221, type: "N", label: "Código para Protesto" },
      { name: "prazo_protesto", start: 222, end: 223, type: "N", label: "Número de Dias para Protesto" },
      { name: "codigo_baixa", start: 224, end: 224, type: "N", label: "Código para Baixa/Devolução" },
      { name: "prazo_baixa", start: 225, end: 227, type: "N", label: "Número de Dias para Baixa/Devolução" },
      { name: "codigo_moeda", start: 228, end: 229, type: "N", label: "Código da Moeda" },
      { name: "numero_contrato", start: 230, end: 239, type: "N", label: "Número do Contrato" },
      { name: "uso_exclusivo_febraban", start: 240, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN" },
    ]
  },
  segmento_q: {
    label: "Segmento Q - Dados do Pagador",
    segmento_id: "Q",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº do Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "Q" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 15, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "codigo_movimento", start: 16, end: 17, type: "N", label: "Cód. Mov." },
      { name: "pagador_tipo_inscricao", start: 18, end: 18, type: "N", label: "Inscrição Tipo" },
      { name: "pagador_numero_inscricao", start: 19, end: 33, type: "N", label: "Inscrição Número" },
      { name: "pagador_nome", start: 34, end: 73, type: "A", label: "Nome" },
      { name: "pagador_endereco", start: 74, end: 113, type: "A", label: "Endereço" },
      { name: "pagador_bairro", start: 114, end: 128, type: "A", label: "Bairro" },
      { name: "pagador_cep", start: 129, end: 133, type: "N", label: "CEP" },
      { name: "pagador_cep_sufixo", start: 134, end: 136, type: "N", label: "Sufixo do CEP" },
      { name: "pagador_cidade", start: 137, end: 151, type: "A", label: "Cidade" },
      { name: "pagador_uf", start: 152, end: 153, type: "A", label: "UF", rule: "validateUF" },
      { name: "sacador_tipo_inscricao", start: 154, end: 154, type: "N", label: "Inscrição Tipo (Sacador)" },
      { name: "sacador_numero_inscricao", start: 155, end: 169, type: "N", label: "Inscrição Número (Sacador)" },
      { name: "sacador_nome", start: 170, end: 209, type: "A", label: "Nome do Sacador/Avalista" },
      { name: "codigo_banco_correspondente", start: 210, end: 212, type: "N", label: "Banco Correspondente" },
      { name: "nosso_numero_banco_correspondente", start: 213, end: 232, type: "A", label: "Nosso Núm. Bco. Correspondente" },
      { name: "uso_exclusivo_febraban_2", start: 233, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " }
    ]
  },
  segmento_r: {
    label: "Segmento R - Descontos/Multas",
    segmento_id: "R",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº do Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "R" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 15, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "codigo_movimento", start: 16, end: 17, type: "N", label: "Cód. Mov." },
      { name: "desconto_2_codigo", start: 18, end: 18, type: "N", label: "Cód. Desc. 2" },
      { name: "desconto_2_data", start: 19, end: 26, type: "N", label: "Data Desc. 2" },
      { name: "desconto_2_valor", start: 27, end: 41, type: "N", label: "Valor/Percentual Desc. 2" },
      { name: "desconto_3_codigo", start: 42, end: 42, type: "N", label: "Cód. Desc. 3" },
      { name: "desconto_3_data", start: 43, end: 50, type: "N", label: "Data Desc. 3" },
      { name: "desconto_3_valor", start: 51, end: 65, type: "N", label: "Valor/Percentual Desc. 3" },
      { name: "multa_codigo", start: 66, end: 66, type: "A", label: "Cód. Multa" },
      { name: "multa_data", start: 67, end: 74, type: "N", label: "Data da Multa" },
      { name: "multa_valor", start: 75, end: 89, type: "N", label: "Multa Valor/Percentual" },
      { name: "informacao_pagador", start: 90, end: 99, type: "A", label: "Informação ao Pagador" },
      { name: "mensagem_3", start: 100, end: 139, type: "A", label: "Mensagem 3" },
      { name: "mensagem_4", start: 140, end: 179, type: "A", label: "Mensagem 4" },
      { name: "uso_exclusivo_febraban_2", start: 180, end: 199, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "cod_ocor_pagador", start: 200, end: 207, type: "N", label: "Cód. Ocor. do Pagador" },
      { name: "debito_banco", start: 208, end: 210, type: "N", label: "Banco para Débito" },
      { name: "debito_agencia", start: 211, end: 215, type: "N", label: "Agência para Débito" },
      { name: "debito_agencia_dv", start: 216, end: 216, type: "A", label: "DV Agência Débito" },
      { name: "debito_conta", start: 217, end: 228, type: "N", label: "Conta para Débito" },
      { name: "debito_conta_dv", start: 229, end: 229, type: "A", label: "DV Conta Débito" },
      { name: "debito_dv_ag_conta", start: 230, end: 230, type: "A", label: "DV Ag/Conta Débito" },
      { name: "aviso_debito_automatico", start: 231, end: 231, type: "N", label: "Aviso Débito Automático" },
      { name: "uso_exclusivo_febraban_3", start: 232, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " }
    ]
  },
  segmento_t: {
    label: "Segmento T - Confirmação (Retorno)",
    segmento_id: "T",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº do Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "T" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 15, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "codigo_movimento", start: 16, end: 17, type: "N", label: "Cód. Mov." },
      { name: "agencia_mantenedora", start: 18, end: 22, type: "N", label: "Agência" },
      { name: "agencia_dv", start: 23, end: 23, type: "A", label: "DV Agência" },
      { name: "numero_conta", start: 24, end: 35, type: "N", label: "Conta Corrente" },
      { name: "conta_dv", start: 36, end: 36, type: "A", label: "DV Conta" },
      { name: "agencia_conta_dv", start: 37, end: 37, type: "A", label: "DV Ag/Conta" },
      { name: "nosso_numero", start: 38, end: 57, type: "A", label: "Nosso Número" },
      { name: "carteira", start: 58, end: 58, type: "N", label: "Carteira" },
      { name: "numero_documento", start: 59, end: 73, type: "A", label: "Nº Documento" },
      { name: "vencimento", start: 74, end: 81, type: "N", label: "Vencimento" },
      { name: "valor_titulo", start: 82, end: 96, type: "N", label: "Valor Nominal" },
      { name: "banco_recebedor", start: 97, end: 99, type: "N", label: "Banco Cobr./Receb." },
      { name: "agencia_recebedora", start: 100, end: 104, type: "N", label: "Agência Cobr./Receb." },
      { name: "agencia_recebedora_dv", start: 105, end: 105, type: "A", label: "DV Ag. Recebedora" },
      { name: "identificacao_titulo_empresa", start: 106, end: 130, type: "A", label: "Identific. Título na Empresa" },
      { name: "codigo_moeda", start: 131, end: 132, type: "N", label: "Moeda" },
      { name: "pagador_tipo_inscricao", start: 133, end: 133, type: "N", label: "Pagador Tipo Insc." },
      { name: "pagador_numero_inscricao", start: 134, end: 148, type: "N", label: "Pagador Número Insc." },
      { name: "pagador_nome", start: 149, end: 188, type: "A", label: "Pagador Nome" },
      { name: "numero_contrato", start: 189, end: 198, type: "N", label: "Nº Contrato" },
      { name: "valor_tarifas", start: 199, end: 213, type: "N", label: "Valor Tarifas/Custas" },
      { name: "motivo_ocorrencia", start: 214, end: 223, type: "A", label: "Motivo Ocorrência" },
      { name: "uso_exclusivo_febraban_2", start: 224, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " }
    ]
  },
  segmento_u: {
    label: "Segmento U - Pagamento (Retorno)",
    segmento_id: "U",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº do Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "U" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 15, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "codigo_movimento", start: 16, end: 17, type: "N", label: "Cód. Mov." },
      { name: "juros_multa_encargos", start: 18, end: 32, type: "N", label: "Juros/Multa/Encargos" },
      { name: "valor_desconto", start: 33, end: 47, type: "N", label: "Valor Desconto" },
      { name: "valor_abatimento", start: 48, end: 62, type: "N", label: "Valor Abatimento" },
      { name: "valor_iof", start: 63, end: 77, type: "N", label: "Valor IOF" },
      { name: "valor_pago", start: 78, end: 92, type: "N", label: "Valor Pago" },
      { name: "valor_liquido", start: 93, end: 107, type: "N", label: "Valor Líquido" },
      { name: "outras_despesas", start: 108, end: 122, type: "N", label: "Outras Despesas" },
      { name: "outros_creditos", start: 123, end: 137, type: "N", label: "Outros Créditos" },
      { name: "data_ocorrencia", start: 138, end: 145, type: "N", label: "Data Ocorrência" },
      { name: "data_credito", start: 146, end: 153, type: "N", label: "Data Crédito" },
      { name: "ocor_pagador_codigo", start: 154, end: 157, type: "A", label: "Cód. Ocorrência Pagador" },
      { name: "ocor_pagador_data", start: 158, end: 165, type: "N", label: "Data Ocorrência Pagador" },
      { name: "ocor_pagador_valor", start: 166, end: 180, type: "N", label: "Valor Ocorrência Pagador" },
      { name: "ocor_pagador_compl", start: 181, end: 210, type: "A", label: "Compl. Ocorrência Pagador" },
      { name: "codigo_banco_corresp", start: 211, end: 213, type: "N", label: "Cód. Banco Corresp." },
      { name: "nosso_numero_banco_corresp", start: 214, end: 233, type: "N", label: "Nosso Núm. Banco Corresp." },
      { name: "uso_exclusivo_febraban_2", start: 234, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " }
    ]
  },
  segmento_a: {
    label: "Segmento A - Pagamento",
    segmento_id: "A",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "A" },
      { name: "tipo_movimento", start: 15, end: 15, type: "N", label: "Tipo Movimento" },
      { name: "codigo_instrucao_movimento", start: 16, end: 17, type: "N", label: "Cód. Instrução" },
      { name: "codigo_camara_centralizadora", start: 18, end: 20, type: "N", label: "Câmara" },
      { name: "codigo_banco_favorecido", start: 21, end: 23, type: "N", label: "Banco Favorecido" },
      { name: "agencia_mantenedora", start: 24, end: 28, type: "N", label: "Agência" },
      { name: "agencia_dv", start: 29, end: 29, type: "A", label: "DV Agência" },
      { name: "numero_conta", start: 30, end: 41, type: "N", label: "Conta Corrente" },
      { name: "conta_dv", start: 42, end: 42, type: "A", label: "DV Conta" },
      { name: "agencia_conta_dv", start: 43, end: 43, type: "A", label: "DV Ag/Conta" },
      { name: "nome_favorecido", start: 44, end: 73, type: "A", label: "Nome Favorecido" },
      { name: "seu_numero", start: 74, end: 93, type: "A", label: "Seu Número (Doc)" },
      { name: "data_pagamento", start: 94, end: 101, type: "N", label: "Data Pagamento", rule: "validateDate" },
      { name: "tipo_moeda", start: 102, end: 104, type: "A", label: "Tipo Moeda" },
      { name: "quantidade_moeda", start: 105, end: 119, type: "N", label: "Qtde Moeda" },
      { name: "valor_pagamento", start: 120, end: 134, type: "N", label: "Valor Pagamento", rule: "validateCurrency" },
      { name: "nosso_numero", start: 135, end: 154, type: "A", label: "Nosso Número" },
      { name: "data_real_pagamento", start: 155, end: 162, type: "N", label: "Data Real", rule: "validateDate" },
      { name: "valor_real_pagamento", start: 163, end: 177, type: "N", label: "Valor Real", rule: "validateCurrency" },
      { name: "informacao_2", start: 178, end: 217, type: "A", label: "Mensagem/PIX Info" },
      { name: "codigo_finalidade_doc", start: 218, end: 219, type: "A", label: "Finalidade DOC" },
      { name: "codigo_finalidade_ted", start: 220, end: 224, type: "A", label: "Finalidade TED" },
      { name: "codigo_finalidade_complementar", start: 225, end: 226, type: "A", label: "Finalidade Compl." },
      { name: "uso_exclusivo_febraban_cnab", start: 227, end: 229, type: "A", label: "Uso Exclusivo FEBRABAN/CNAB", default: " " },
      { name: "aviso_favorecido", start: 230, end: 230, type: "N", label: "Aviso" },
      { name: "ocorrencias", start: 231, end: 240, type: "A", label: "Ocorrências" }
    ]
  },
  segmento_b: {
    label: "Segmento B - Dados Complementares",
    segmento_id: "B",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "B" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 17, type: "A", label: "Uso Exclusivo FEBRABAN/CNAB", default: " " },
      { name: "tipo_inscricao_favorecido", start: 18, end: 18, type: "N", label: "Tipo Inscrição", rule: "validateInscricaoTipo" },
      { name: "numero_inscricao_favorecido", start: 19, end: 32, type: "N", label: "Número Inscrição", rule: "validateCNPJ_CPF" },
      { name: "logradouro", start: 33, end: 62, type: "A", label: "Endereço" },
      { name: "numero", start: 63, end: 67, type: "N", label: "Número" },
      { name: "complemento", start: 68, end: 82, type: "A", label: "Complemento" },
      { name: "bairro", start: 83, end: 97, type: "A", label: "Bairro" },
      { name: "cidade", start: 98, end: 112, type: "A", label: "Cidade" },
      { name: "cep", start: 113, end: 117, type: "N", label: "CEP" },
      { name: "cep_sufixo", start: 118, end: 120, type: "A", label: "Sufixo CEP" },
      { name: "estado", start: 121, end: 122, type: "A", label: "UF", rule: "validateUF" },
      { name: "data_vencimento", start: 123, end: 130, type: "N", label: "Vencimento", rule: "validateDate" },
      { name: "valor_documento", start: 131, end: 145, type: "N", label: "Valor Documento", rule: "validateCurrency" },
      { name: "valor_abatimento", start: 146, end: 160, type: "N", label: "Abatimento", rule: "validateCurrency" },
      { name: "valor_desconto", start: 161, end: 175, type: "N", label: "Desconto", rule: "validateCurrency" },
      { name: "valor_mora", start: 176, end: 190, type: "N", label: "Mora", rule: "validateCurrency" },
      { name: "valor_multa", start: 191, end: 205, type: "N", label: "Multa", rule: "validateCurrency" },
      { name: "codigo_documento_favorecido", start: 206, end: 220, type: "A", label: "Cód. Doc. Favorecido" },
      { name: "aviso", start: 221, end: 221, type: "N", label: "Aviso" },
      { name: "codigo_isPB", start: 222, end: 229, type: "N", label: "ISPB Banco" },
      { name: "uso_exclusivo_febraban_2", start: 230, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN/CNAB", default: " " }
    ]
  },
  segmento_j: {
    label: "Segmento J - Pagamento de Títulos",
    segmento_id: "J",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "J" },
      { name: "tipo_movimento", start: 15, end: 15, type: "N", label: "Tipo Movimento" },
      { name: "codigo_instrucao_movimento", start: 16, end: 17, type: "N", label: "Cód. Instrução" },
      { name: "codigo_barras", start: 18, end: 61, type: "N", label: "Código de Barras" },
      { name: "nome_beneficiario", start: 62, end: 91, type: "A", label: "Beneficiário" },
      { name: "data_vencimento", start: 92, end: 99, type: "N", label: "Vencimento (Nominal)", rule: "validateDate" },
      { name: "valor_titulo", start: 100, end: 114, type: "N", label: "Valor Título", rule: "validateCurrency" },
      { name: "valor_desconto_abatimento", start: 115, end: 129, type: "N", label: "Desconto/Abatimento", rule: "validateCurrency" },
      { name: "valor_mora_multa", start: 130, end: 144, type: "N", label: "Mora/Multa", rule: "validateCurrency" },
      { name: "data_pagamento", start: 145, end: 152, type: "N", label: "Data Pagamento", rule: "validateDate" },
      { name: "valor_pagamento", start: 153, end: 167, type: "N", label: "Valor Pagamento", rule: "validateCurrency" },
      { name: "quantidade_moeda", start: 168, end: 182, type: "N", label: "Qtde Moeda" },
      { name: "referencia_pagador", start: 183, end: 202, type: "A", label: "Referência Pagador" },
      { name: "nosso_numero", start: 203, end: 222, type: "A", label: "Nosso Número" },
      { name: "codigo_moeda", start: 223, end: 224, type: "N", label: "Cód. Moeda" },
      { name: "uso_exclusivo_febraban", start: 225, end: 230, type: "A", label: "Uso Exclusivo FEBRABAN/CNAB", default: " " },
      { name: "ocorrencias", start: 231, end: 240, type: "A", label: "Ocorrências" }
    ]
  },
  header_lote: {
    label: "Header de Lote",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "1" },
      { name: "tipo_operacao", start: 9, end: 9, type: "A", label: "Operação" },
      { name: "tipo_servico", start: 10, end: 11, type: "N", label: "Serviço" },
      { name: "forma_lancamento", start: 12, end: 13, type: "N", label: "Forma Lançamento" },
      { name: "layout_lote", start: 14, end: 16, type: "N", label: "Layout Lote" },
      { name: "uso_exclusivo_febraban_1", start: 17, end: 17, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "empresa_tipo_inscricao", start: 18, end: 18, type: "N", label: "Empresa Tipo Insc.", rule: "validateInscricaoTipo" },
      { name: "empresa_numero_inscricao", start: 19, end: 32, type: "N", label: "Empresa Número Insc.", rule: "validateCNPJ_CPF" },
      { name: "codigo_convenio", start: 33, end: 52, type: "A", label: "Código Convênio" },
      { name: "agencia_mantenedora", start: 53, end: 57, type: "N", label: "Agência" },
      { name: "agencia_dv", start: 58, end: 58, type: "A", label: "DV Agência" },
      { name: "numero_conta", start: 59, end: 70, type: "N", label: "Conta Corrente" },
      { name: "conta_dv", start: 71, end: 71, type: "A", label: "DV Conta" },
      { name: "agencia_conta_dv", start: 72, end: 72, type: "A", label: "DV Ag/Conta" },
      { name: "nome_empresa", start: 73, end: 102, type: "A", label: "Nome Empresa" },
      { name: "informacao_1", start: 103, end: 142, type: "A", label: "Mensagem 1" },
      { name: "endereco_empresa", start: 143, end: 172, type: "A", label: "Endereço Empresa" },
      { name: "numero_endereco", start: 173, end: 177, type: "N", label: "Número" },
      { name: "complemento_endereco", start: 178, end: 192, type: "A", label: "Complemento" },
      { name: "cidade_empresa", start: 193, end: 212, type: "A", label: "Cidade" },
      { name: "cep_empresa", start: 213, end: 217, type: "N", label: "CEP" },
      { name: "cep_sufixo_empresa", start: 218, end: 220, type: "A", label: "Sufixo CEP" },
      { name: "estado_empresa", start: 221, end: 222, type: "A", label: "UF" },
      { name: "uso_exclusivo_febraban_2", start: 223, end: 230, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "ocorrencias", start: 231, end: 240, type: "A", label: "Ocorrências" }
    ]
  },
  trailer_lote: {
    label: "Trailer de Lote",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "5" },
      { name: "uso_exclusivo_febraban_1", start: 9, end: 17, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "quantidade_registros", start: 18, end: 23, type: "N", label: "Quantidade Registros" },
      { name: "somatorio_valores", start: 24, end: 41, type: "N", label: "Somatório Valores" },
      { name: "somatorio_quantidade_moedas", start: 42, end: 59, type: "N", label: "Somatório Qtde Moedas" },
      { name: "numero_aviso_debito", start: 60, end: 65, type: "N", label: "Aviso Débito" },
      { name: "uso_exclusivo_febraban_2", start: 66, end: 230, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "ocorrencias", start: 231, end: 240, type: "A", label: "Ocorrências" }
    ]
  },
  trailer_arquivo: {
    label: "Trailer de Arquivo",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote", default: "9999" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "9" },
      { name: "uso_exclusivo_febraban_1", start: 9, end: 17, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "quantidade_lotes", start: 18, end: 23, type: "N", label: "Quantidade de Lotes" },
      { name: "quantidade_registros", start: 24, end: 29, type: "N", label: "Quantidade de Registros" },
      { name: "quantidade_contas", start: 30, end: 35, type: "N", label: "Quantidade de Contas" },
      { name: "uso_exclusivo_febraban_2", start: 36, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " }
    ]
  },
  // Adding J52 as it was mentioned as a special case
  segmento_j52: {
    label: "Segmento J-52 - Identificação (Extensão)",
    segmento_id: "J52",
    fields: [
      { name: "codigo_banco", start: 1, end: 3, type: "N", label: "Banco" },
      { name: "lote_servico", start: 4, end: 7, type: "N", label: "Lote" },
      { name: "tipo_registro", start: 8, end: 8, type: "N", label: "Registro", default: "3" },
      { name: "numero_sequencial", start: 9, end: 13, type: "N", label: "Nº Registro" },
      { name: "codigo_segmento", start: 14, end: 14, type: "A", label: "Segmento", default: "J" },
      { name: "uso_exclusivo_febraban_1", start: 15, end: 15, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " },
      { name: "codigo_movimento", start: 16, end: 17, type: "N", label: "Cód. Mov." },
      { name: "identificacao_registro_opcional", start: 18, end: 19, type: "N", label: "Identif. Opcional", default: "52" },
      { name: "pagador_tipo_inscricao", start: 20, end: 20, type: "N", label: "Pagador Tipo Insc." },
      { name: "pagador_numero_inscricao", start: 21, end: 35, type: "N", label: "Pagador Número Insc." },
      { name: "pagador_nome", start: 36, end: 75, type: "A", label: "Pagador Nome" },
      { name: "beneficiario_tipo_inscricao", start: 76, end: 76, type: "N", label: "Benefic. Tipo Insc." },
      { name: "beneficiario_numero_inscricao", start: 77, end: 91, type: "N", label: "Benefic. Número Insc." },
      { name: "beneficiario_nome", start: 92, end: 131, type: "A", label: "Benefic. Nome" },
      { name: "sacador_tipo_inscricao", start: 132, end: 132, type: "N", label: "Sacador Tipo Insc." },
      { name: "sacador_numero_inscricao", start: 133, end: 147, type: "N", label: "Sacador Número Insc." },
      { name: "sacador_nome", start: 148, end: 187, type: "A", label: "Sacador Nome" },
      { name: "uso_exclusivo_febraban_2", start: 188, end: 240, type: "A", label: "Uso Exclusivo FEBRABAN", default: " " }
    ]
  }
};
