export const GENERIC_RULES = [
  { id: "G001", name: "Código do Banco", desc: "Código do Banco na Compensação", validation: "numeric" },
  { id: "G002", name: "Lote de Serviço", desc: "Número sequencial para identificar o lote", validation: "batchNumber" },
  { id: "G003", name: "Tipo de Registro", desc: "Identifica a função da linha", validation: "oneOf", values: ["0", "1", "2", "3", "4", "5", "9"], options: [
    { value: "0", label: "Header de Arquivo", description: "Primeira linha do arquivo, contém informações gerais do transmissor." },
    { value: "1", label: "Header de Lote", description: "Início de um lote de serviço." },
    { value: "2", label: "Registros Iniciais de Lote", description: "Dados complementares do lote." },
    { value: "3", label: "Segmentos de Detalhe", description: "Registros que contêm os dados dos títulos/pagamentos (A, B, J, P, Q, R...)." },
    { value: "4", label: "Registros Finais de Lote", description: "Dados complementares de fechamento do lote." },
    { value: "5", label: "Trailer de Lote", description: "Final de um lote de serviço, contém totais do lote." },
    { value: "9", label: "Trailer de Arquivo", description: "Última linha do arquivo, contém totais gerais." }
  ]},
  { id: "G004", name: "Uso Exclusivo FEBRABAN", desc: "Campo de preenchimento com brancos ou zeros", validation: "filler" },
  { id: "G005", name: "Tipo de Inscrição", desc: "Tipo de documento da empresa/pessoa", validation: "oneOf", values: ["0", "1", "2", "3", "9"], options: [
    { value: "0", label: "Isento / Não Informado", description: "Quando não há documento ou é isento de inscrição." },
    { value: "1", label: "CPF", description: "Pessoa Física (11 dígitos úteis)." },
    { value: "2", label: "CGC / CNPJ", description: "Pessoa Jurídica (14 dígitos úteis)." },
    { value: "3", label: "PIS / PASEP", description: "Número de inscrição no PIS/PASEP." },
    { value: "9", label: "Outros", description: "Outros tipos de identificação não listados." }
  ]},
  { id: "G006", name: "Número de Inscrição", desc: "Número de CPF ou CNPJ conforme G005", validation: "dynamicTaxId" },
  { id: "G007", name: "Código do Convênio", desc: "Código do convênio firmado entre a Empresa e o Banco", validation: "alphanumeric" },
  { id: "G008", name: "Agência Mantenedora", desc: "Código da Agência sem o dígito verificador", validation: "numeric" },
  { id: "G009", name: "Dígito Verificador da Agência", desc: "DV da agência mantenedora", validation: "alphanumeric" },
  { id: "G010", name: "Número da Conta Corrente", desc: "Número da conta corrente sem o dígito verificador", validation: "numeric" },
  { id: "G011", name: "Dígito Verificador da Conta", desc: "DV da conta corrente", validation: "alphanumeric" },
  { id: "G012", name: "Dígito Verificador da Ag/Conta", desc: "DV do par Agência/Conta", validation: "alphanumeric" },
  { id: "G013", name: "Nome da Empresa/Favorecido", desc: "Nome que identifica a entidade", validation: "alphanumeric" },
  { id: "G015", name: "Cód. Remessa/Retorno", desc: "Identifica a direção do arquivo", validation: "oneOf", values: ["1", "2"], options: [
    { value: "1", label: "Remessa", description: "Arquivo enviado da Empresa para o Banco (Instruções)." },
    { value: "2", label: "Retorno", description: "Arquivo enviado do Banco para a Empresa (Confirmações/Liquidações)." }
  ]},
  { id: "G016", name: "Data de Geração", desc: "Data no formato DDMMAAAA", validation: "date" },
  { id: "G017", name: "Hora de Geração", desc: "Hora no formato HHMMSS", validation: "time" },
  { id: "G018", name: "Sequencial NSA", desc: "Número Sequencial do Arquivo", validation: "numeric" },
  { id: "G019", name: "Versão do Layout", desc: "Número da versão do layout (Ex: 103)", validation: "numeric" },
  { id: "G025", name: "Tipo de Serviço", desc: "Finalidade do lote", validation: "oneOf", values: ["01", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "20", "22", "23", "25", "26", "29", "30", "32", "33", "34", "40", "41", "50", "60", "70", "75", "77", "80", "90", "98"], options: [
    { value: "01", label: "Cobrança", description: "Serviços de cobrança de títulos." },
    { value: "03", label: "Boleto de Pagamento", description: "Processamento de boletos bancários." },
    { value: "04", label: "Conciliação Bancária", description: "Envio de extratos para conferência de saldos." },
    { value: "05", label: "Débitos", description: "Instruções de débitos diversos." },
    { value: "06", label: "Custódia de Cheques", description: "Gestão de cheques para custódia." },
    { value: "07", label: "Gestão de Caixa", description: "Movimentações para gestão financeira." },
    { value: "08", label: "Consulta/Informação de Margem", description: "Consulta de limites e margens." },
    { value: "09", label: "Averbação de Empréstimo/Consignação", description: "Registro de empréstimos consignados." },
    { value: "10", label: "Pagamento Dividendos", description: "Distribuição de lucros aos acionistas." },
    { value: "11", label: "Manutenção de Consignado", description: "Gestão de contratos de consignação." },
    { value: "12", label: "Consignação de Empréstimo", description: "Novo contrato de consignação." },
    { value: "13", label: "Glosa de Empréstimo", description: "Cancelamento ou suspensão de consignação." },
    { value: "14", label: "Consulta de Empréstimo", description: "Verificação de status de empréstimo." },
    { value: "20", label: "Pagamento Fornecedor", description: "Liquidação de faturas de fornecedores." },
    { value: "22", label: "Pagamento de Contas, Tributos e Impostos", description: "Quitação de boletos de concessionárias e impostos." },
    { value: "25", label: "Comprador", description: "Operações de compra." },
    { value: "26", label: "Vendedor", description: "Operações de venda." },
    { value: "29", label: "Lançamento do Crédito Imobiliário", description: "Crédito referente a financiamento habitacional." },
    { value: "30", label: "Pagamento Salários", description: "Crédito de folha de pagamento de funcionários." },
    { value: "32", label: "Pagamento de Honorários", description: "Pagamento de serviços profissionais prestados." },
    { value: "33", label: "Pagamento de Bolsa Auxílio", description: "Crédito para estagiários ou beneficiários." },
    { value: "34", label: "Pagamento de Precatórios", description: "Liquidação de dívidas judiciais do governo." },
    { value: "40", label: "Consulta de Saldo", description: "Verificação de disponibilidade em conta." },
    { value: "41", label: "Consulta de Extrato", description: "Verificação de movimentações recentes." },
    { value: "50", label: "Gestão de Caixa", description: "Operações estruturadas de tesouraria." },
    { value: "60", label: "Recebimento", description: "Identificação de créditos recebidos." },
    { value: "70", label: "Pagamento Letra de Câmbio", description: "Resgate ou pagamento de títulos de crédito." },
    { value: "75", label: "Pagamento de Municípios", description: "Transferências para prefeituras." },
    { value: "77", label: "Pagamento de Estado", description: "Transferências para governos estaduais." },
    { value: "80", label: "Pagamento Eletrônico Tributos", description: "Quitação de impostos federais (DARF, GPS)." },
    { value: "90", label: "Pagamento de Empréstimos/Financiamentos", description: "Liquidação de parcelas de crédito." },
    { value: "98", label: "Pagamentos Diversos", description: "Outros tipos de pagamentos não especificados." }
  ]},
  { id: "G028", name: "Tipo de Operação", desc: "Natureza dos lançamentos no lote", validation: "oneOf", values: ["C", "D", "E", "G", "I", "R", "T"], options: [
    { value: "C", label: "Lançamentos a Crédito", description: "Entrada de recursos na conta do favorecido." },
    { value: "D", label: "Lançamentos a Débito", description: "Saída de recursos da conta do pagador." },
    { value: "E", label: "Extrato para Conciliação", description: "Fluxo de informações de extrato." },
    { value: "G", label: "Extrato para Gestão de Caixa", description: "Fluxo de informações para tesouraria." },
    { value: "I", label: "Informações de Títulos Capturados", description: "Dados de títulos processados." },
    { value: "R", label: "Arquivos de Remessa", description: "Fluxo Empresa -> Banco (Instruções)." },
    { value: "T", label: "Arquivos de Retorno", description: "Fluxo Banco -> Empresa (Confirmações)." }
  ]},
  { id: "G029", name: "Forma de Lançamento", desc: "Meio de pagamento/recebimento", validation: "oneOf", values: ["01", "02", "03", "04", "05", "10", "11", "16", "17", "18", "19", "20", "21", "30", "31", "40", "41", "43", "44", "45", "47", "50", "70", "71", "72", "73", "80", "81"], options: [
    { value: "01", label: "Crédito em Conta Corrente", description: "Transferência interna entre contas no mesmo banco." },
    { value: "02", label: "Cheque Pagamento / Administrativo", description: "Emissão de cheque para quitação." },
    { value: "03", label: "DOC / TED", description: "Transferência interbancária via compensação ou SPB." },
    { value: "04", label: "Cartão Salário", description: "Crédito em cartão específico para folha." },
    { value: "05", label: "Crédito em Conta Poupança", description: "Transferência interna para poupança no mesmo banco." },
    { value: "10", label: "OP à Disposição", description: "Ordem de Pagamento para saque em guichê." },
    { value: "11", label: "Pagamento de Contas e Tributos", description: "Quitação de boletos com código de barras." },
    { value: "16", label: "Tributos - DARF Normal", description: "Pagamento de impostos federais normais." },
    { value: "17", label: "Tributos - GPS", description: "Guia da Previdência Social." },
    { value: "18", label: "Tributos - DARF Simples", description: "Imposto para empresas do Simples Nacional." },
    { value: "19", label: "Tributos - IPTU", description: "Imposto Predial e Territorial Urbano." },
    { value: "20", label: "Tributos - DARJ", description: "Documento de Arrecadação do Rio de Janeiro." },
    { value: "21", label: "Tributos - GARE-SP", description: "Guia de Arrecadação de Receitas Estaduais de SP." },
    { value: "30", label: "Liquidação de Títulos no Próprio Banco", description: "Pagamento de boleto emitido pelo mesmo banco." },
    { value: "31", label: "Pagamento de Títulos de Outros Bancos", description: "Pagamento de boleto via compensação." },
    { value: "40", label: "Extrato de Conta Corrente", description: "Lançamento informativo de extrato." },
    { value: "41", label: "TED - Outra Titularidade", description: "TED para CPFs/CNPJs diferentes do pagador." },
    { value: "43", label: "TED - Mesma Titularidade", description: "TED entre contas do mesmo titular." },
    { value: "44", label: "TED para Transferência de Conta Investimento", description: "Movimentação de fundos para investimento." },
    { value: "45", label: "PIX", description: "Pagamento instantâneo via arranjo PIX." },
    { value: "47", label: "Transferência para Conta Corrente", description: "Transferência entre contas de mesma titularidade internamente." },
    { value: "50", label: "Débito em Conta Corrente", description: "Lançamento de débito direto." },
    { value: "70", label: "Extrato para Gestão de Caixa", description: "Lançamento consolidado para tesouraria." },
    { value: "71", label: "Depósito Judicial em Conta Corrente", description: "Bloqueio ou depósito via ordem judicial." },
    { value: "72", label: "Depósito Judicial em Conta Poupança", description: "Bloqueio ou depósito judicial em poupança." },
    { value: "73", label: "Extrato de Conta Investimento", description: "Informação de movimentação em investimentos." },
    { value: "80", label: "Pagamento de Tributos Municipais (ISS)", description: "Quitação de imposto sobre serviços." },
    { value: "81", label: "Pagamento de Tributos Estaduais (ICMS)", description: "Quitação de imposto sobre circulação de mercadorias." }
  ]},
  { id: "G031", name: "Outras Informações", desc: "Informações complementares (PIX/SIAPE/Mensagens)", validation: "pixKey" },
  { id: "G036", name: "Estado/UF", desc: "Sigla da Unidade da Federação", validation: "uf" },
  { id: "G040", name: "Tipo de Moeda (Alfa)", desc: "Identificação da Moeda (Alfa)", validation: "oneOf", values: ["BTN", "BRL", "USD", "PTE", "FRF", "CHF", "JPY", "GBP", "DEM", "TRD", "UPC", "UPF", "UFR", "XEU"] },
  { id: "G041", name: "Quantidade da Moeda", desc: "Quantidade de unidades da moeda", validation: "amount" },
  { id: "G043", name: "Nº Documento (Banco)", desc: "Número do documento atribuído pelo Banco", validation: "alphanumeric" },
  { id: "G059", name: "Ocorrências (Retorno)", desc: "Códigos de ocorrências para retorno", validation: "alphanumeric" },
  { id: "G060", name: "Tipo de Movimento", desc: "Tipo de instrução de movimento", validation: "oneOf", values: ["0", "1", "2", "3", "4", "5", "7", "9"], options: [
    { value: "0", label: "Inclusão", description: "Solicita a inclusão de um novo registro liberado para processamento." },
    { value: "1", label: "Consulta", description: "Solicita consulta de dados do registro." },
    { value: "2", label: "Suspensão", description: "Solicita o bloqueio temporário do registro." },
    { value: "3", label: "Estorno / Exclusão", description: "Solicita o cancelamento de um registro anteriormente enviado." },
    { value: "4", label: "Reativação", description: "Solicita o desbloqueio do registro." },
    { value: "5", label: "Alteração", description: "Solicita a modificação de dados de um registro já existente." },
    { value: "7", label: "Liquidação", description: "Indica que o título/pagamento foi liquidado." },
    { value: "9", label: "Exclusão de Lote", description: "Solicita a exclusão de todos os registros do lote." }
  ]},
  { id: "G061", name: "Código Instrução Movimento", desc: "Ação a ser realizada", validation: "numeric" },
  { id: "G064", name: "Nº Documento (Empresa)", desc: "Número do documento atribuído pela Empresa", validation: "alphanumeric" },
  { id: "G065", name: "Código da Moeda (Num)", desc: "Identificação da Moeda (Numérico)", validation: "oneOf", values: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"], options: [
    { value: "09", label: "Real (BRL)", description: "Moeda oficial do Brasil." }
  ]},
  { id: "G067", name: "Cód. Registro Opcional", desc: "Identifica se o registro é complementar (ex: 52)", validation: "oneOf", values: ["52"] },
  { id: "G081", name: "Situação Saldo Inicial", desc: "Débito ou Crédito", validation: "oneOf", values: ["C", "D"] },
  { id: "G082", name: "Posição Saldo Inicial", desc: "Composição do saldo", validation: "oneOf", values: ["P", "F", "I"] },
  { id: "G032", name: "Endereço", desc: "Logradouro, Número ou Complemento", validation: "alphanumeric" },
  { id: "G033", name: "Cidade", desc: "Nome da Cidade", validation: "alphanumeric" },
  { id: "G034", name: "CEP", desc: "Código de Endereçamento Postal", validation: "numeric" },
  { id: "G035", name: "Complemento CEP", desc: "Complemento do CEP", validation: "alphanumeric" },
  { id: "G042", name: "Valor Nominal", desc: "Valor do documento ou lançamento", validation: "amount" },
  { id: "G044", name: "Data Vencimento", desc: "Data de vencimento nominal (DDMMAAAA)", validation: "date" },
  { id: "G045", name: "Valor Abatimento", desc: "Valor do abatimento", validation: "amount" },
  { id: "G046", name: "Valor Desconto", desc: "Valor do desconto", validation: "amount" },
  { id: "G047", name: "Valor Mora", desc: "Valor dos juros de mora", validation: "amount" },
  { id: "G048", name: "Valor Multa", desc: "Valor da multa", validation: "amount" },
  { id: "G057", name: "Quantidade de Registros do Lote", desc: "Somatória da quantidade de registros do lote", validation: "numeric" },
  { id: "G058", name: "Somatória de Quantidade de Moedas", desc: "Somatória de quantidade de moedas do lote", validation: "numeric" },
  { id: "G066", name: "Número Aviso de Débito", desc: "Número aviso de débito", validation: "numeric" },
  { id: "G056", name: "Quantidade total de registros do arquivo", desc: "Somatória da quantidade total de registros do arquivo", validation: "numeric" }
];
